package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"app/db"
	"app/graph/model"
	"app/infrastructures/api_client"
	"app/types"
	"context"
	"fmt"

	_ "github.com/lib/pq"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Result, error) {
	db := db.OpenDB()
	post := &types.Post{Content: input.Content}
	_, err := db.NewInsert().Model(post).Exec(ctx)
	if err != nil {
		return &model.Result{Response: false}, err
	}

	api_client.Main(ctx)
	return &model.Result{Response: true}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
